import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/shared/Header'
import Footer from './components/shared/Footer'
import { Toaster } from 'react-hot-toast'
import TanstackQueryProvider from './TanstackQueryProvider'
import AuthProvider from './components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Header></Header>

          <div className=' max-w-7xl mx-auto'>
            <Toaster />
            <TanstackQueryProvider>
              {children}
            </TanstackQueryProvider>
          </div>
          <Footer></Footer>

        </body>
      </AuthProvider>
    </html>
  )
}
